### ISSUE TITLE
Need Sound or Voice-Over Audio Clips

### ISSUE THREAD

**Issue by briankb** [maker-dot-space/arena-controller#1]
need the sounds and audio clips to be used in the program

**Comment by briankb** [comment]
suggestions for possible voice-overs

tap out state - "TTTTTTT TAP OUT!" really loud and with repetitive T at beginning. I think I've heard this exactly from some 80/90's video game.

**Comment by makAR-rudy** [comment]
Lilly wants different sounds but for now I have these done


[Sounds v1.zip](https://github.com/maker-dot-space/arena-controller/files/3747393/Sounds.v1.zip)

**Comment by briankb** [comment]
empty
